Repository GabrielNsiah/Plant-Health-Monitoring-at-LNMH, pull requests merged in 2024-11, with the labels that each got.

#41 Add badge folder and fix badge creation
  .github/badges/pylint.svg
  .github/badges/test.svg
  .github/workflows/deployment.yml
  README.md
Labels: bug

#47 Fixing the pylint badge appearance
  .github/badges/pylint.svg
  .github/workflows/deployment.yml
Labels: fix

#51 changes to schema constraints under plant table
  database/schema.sql
Labels: enhancement, fix

#52 Create eventbridge terraform
  .gitignore
  terraform/main.tf
Labels: enhancement

#53 Finished initial load script
  .github/badges/pylint.svg
  pipeline/load.py
Labels: documentation, enhancement

#55 Pytest for load
  .github/badges/test.svg
  pipeline/test_load.py
Labels: enhancement

#56 54 composite
  pipeline/etl.py
  pipeline/extract.py
  pipeline/load.py
  pipeline/transform.py
Labels: documentation

#57 Fixing Workflow
  .github/badges/test.svg
  .github/workflows/deployment.yml
Labels: bug, fix

#59 Dockerfile created
  pipeline/Dockerfile
Labels: enhancement

#61 Get ready for lambda
  .github/badges/test.svg
  pipeline/Dockerfile
  pipeline/load.py
  pipeline/requirements.txt
  pipeline/transform.py
Labels: enhancement

#62 Fix load test
  pipeline/test_load.py
Labels: fix

#64 Fix testing
  .github/badges/test.svg
  .github/workflows/deployment.yml
  README.md
Labels: bug, fix

#65 Completed lambda_mover.py script and test file
  .github/badges/test.svg
  .gitignore
  database/lambda_mover.py
  database/reset_db.py
  database/test_existing_recordings.csv
  database/test_lambda_mover.py
  requirements.txt
Labels: enhancement

#66 Fix workflow
  .github/badges/test.svg
  .github/workflows/deployment.yml
Labels: fix

#71 made dockerfile and pushed lambda_mover to ECR
  .github/badges/pylint.svg
  database/dockerfile
  database/requirements.txt
Labels: enhancement

#72 base script for making merged df used for streamlit graphs
  streamlit/base_script.py
Labels: enhancement

#74 Dashboard graphs made
  .DS_Store
  .github/badges/pylint.svg
  .github/badges/test.svg
  .gitignore
  pipeline/load.py
  pipeline/requirements.txt
  requirements.txt
  streamlit/base_script.py
  streamlit/combined_trends.py
  streamlit/continents.py
  streamlit/dashboard.py
Labels: enhancement

#78 Started Readme
  .github/badges/pylint.svg
  pipeline/README.md
Labels: documentation

#81 Fixing Spelling
  .github/badges/test.svg
  pipeline/README.md
Labels: documentation

#80 77 streamlit readme
  README.md
  streamlit/README.md
Labels: documentation

#82 Fixing Badges
  .DS_Store
  .github/badges/test.svg
  pipeline/README.md
Labels: fix

#84 Fixing capitals
  README.md
Labels: documentation
